### ISSUE TITLE
WPF にて使用する際、一部のコードをリファクタリングする必要性がある？

### ISSUE THREAD

**Issue by Asteriskx** [Legato-Dev/AlbumArtExtraction#7]
ID3 v2.3, 2,4 のものに関して書いてみたので、展開します。
ローカルで変更しているので、コミットとかはしていません。
※画像が取得できることは確認済み。

修正したほうが良ければ、連絡お願いします。

- メソッドの戻り値変更＋画像変換ロジック一部変更
```
private BitmapImage _ReadPictureInFrameHeaders(Stream file) {
	// byte データを画像として変換する
	using (var memory = new MemoryStream(imageSource.ToArray()))
	{
		var bitmap = new BitmapImage();
		bitmap.BeginInit();
		bitmap.StreamSource = memory;
		bitmap.CacheOption = BitmapCacheOption.OnLoad;
		bitmap.EndInit();
		bitmap.Freeze();
		return bitmap;
	}
}
```

- メソッドの戻り値変更
`public BitmapImage Extract(string filePath)`

- Interface のメソッド戻り値も変更が必要になりそう。

**Comment by marihachi** [comment]
試してないしBitmapImageの挙動を知らないのでアレだけど、ストリームmemoryはusingで囲って開放してるけど大丈夫なの？メソッドの実行が終わると共にストリームは読み取りできなくなってStreamSourceは解放済みのストリームが入ることになると思うけど..

**Comment by marihachi** [comment]
あと、Extract(string filePath) はより抽象的なリソースを返すほうが良い気がしてきたな。Streamにしようか。
BitmapやBitmapImageへの変換はサポートするにしてもユーティリティとかもっと具体性の強いクラスへ任せるようにしたほうが良さそう

**Comment by marihachi** [comment]
ok
